FROM nikolaik/python-nodejs:python3.7-nodejs13-alpine
LABEL maintainer="Self, subbu322@gmail.com"

RUN apk add --no-cache python python-dev python3 python3-dev curl \
    linux-headers build-base bash git ca-certificates && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    python -V && \
    rm -r /root/.cache

RUN npm -g install serverless
RUN npm install -g newman

RUN mkdir -p /data
WORKDIR /data

COPY . ./

WORKDIR /data/source

#RUN mv serverless.install.yml serverless.yml

RUN serverless plugin install --name serverless-python-requirements@5.1.0 && serverless plugin install --name serverless-wsgi@1.7.6

#RUN rm -f serverless.yml && mv serverless.app.yml serverless.yml

#RUN chmod +x rollbar-deploy.sh

RUN ls -lah

#ENTRYPOINT ["/bin/sh"]
#ENTRYPOINT ["sls"]
