org: svardhineedi
app: slsapi
service: user

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  stage: dev
  region: us-east-1
  iam:
    role: "arn:aws:iam::911681623193:role/slsdemo"

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - '!node_modules/@modulenamespace/*/node_modules/**'
    - '!tmp/**'
    - '!.git/**'
    - '!.vscode/**'
    - '!venv/**'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: user.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'